// <auto-generated />
using System;
using Implementation.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240516173027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LlmApi")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.ModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<long>("ContextTokenCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("ImageSupport")
                        .HasColumnType("boolean");

                    b.Property<bool>("JsonResponseOptimized")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MaxTokenCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelIdentifierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<bool>("VideoSupport")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ModelEntity", "LlmApi");
                });

            modelBuilder.Entity("Domain.Entity.PriceEntity", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("MillionInputTokenPrice")
                        .HasColumnType("integer");

                    b.Property<int>("MillionOutputTokenPrice")
                        .HasColumnType("integer");

                    b.HasKey("ModelId");

                    b.ToTable("PriceEntity", "LlmApi");
                });

            modelBuilder.Entity("Domain.Entity.PromptContentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PromptMessageEntityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PromptMessageEntityId");

                    b.ToTable("PromptContentEntity", "LlmApi");
                });

            modelBuilder.Entity("Domain.Entity.PromptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccessTokenIdentifier")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentMillionInputTokenPrice")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentMillionOutputTokenPrice")
                        .HasColumnType("integer");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InternalModelIdentifier")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("PromptCompletionTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("PromptFinnishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderPromptIdentifier")
                        .HasColumnType("text");

                    b.Property<long>("ResponseMessageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Streamed")
                        .HasColumnType("boolean");

                    b.Property<string>("SystemMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResponseMessageId");

                    b.ToTable("PromptEntity", "LlmApi");
                });

            modelBuilder.Entity("Domain.Entity.PromptMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsUserMessage")
                        .HasColumnType("boolean");

                    b.Property<long?>("PromptEntityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PromptEntityId");

                    b.ToTable("PromptMessageEntity", "LlmApi");
                });

            modelBuilder.Entity("Domain.Entity.ModelEntity", b =>
                {
                    b.HasOne("Domain.Entity.PriceEntity", "Price")
                        .WithOne()
                        .HasForeignKey("Domain.Entity.ModelEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Domain.Entity.PromptContentEntity", b =>
                {
                    b.HasOne("Domain.Entity.PromptMessageEntity", null)
                        .WithMany("Content")
                        .HasForeignKey("PromptMessageEntityId");
                });

            modelBuilder.Entity("Domain.Entity.PromptEntity", b =>
                {
                    b.HasOne("Domain.Entity.PromptMessageEntity", "ResponseMessage")
                        .WithMany()
                        .HasForeignKey("ResponseMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResponseMessage");
                });

            modelBuilder.Entity("Domain.Entity.PromptMessageEntity", b =>
                {
                    b.HasOne("Domain.Entity.PromptEntity", null)
                        .WithMany("Messages")
                        .HasForeignKey("PromptEntityId");
                });

            modelBuilder.Entity("Domain.Entity.PromptEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.Entity.PromptMessageEntity", b =>
                {
                    b.Navigation("Content");
                });
#pragma warning restore 612, 618
        }
    }
}
