name: Build Workflow

on: [pull_request]

jobs:
  docker-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build -t ${{secrets.REGISTRY}}/${{secrets.IMAGE_NAME}}:latest .